apiVersion: v1
kind: Pod
metadata:
  name: nginx #name of Pod
  labels:
    app: nginx # Use this label to express on service
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

 