apiVersion: v1
kind: Service
metadata:
  name: my-service #name of Pod
spec:
  type: NodePort # Service Type
  selector:
    app: nginx # label of your pod
  ports:
    - protocol: TCP
      port: 80 # Internal Port used by container
      targetPort: 80 # Host Port
      nodePort: 30007 #Service Port
